# Generated by Django 6.1.1 on 2026-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(help_text='Contoh: EURUSD', max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('bid_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('ask_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('pair', 'timestamp')},
            },
        ),
    ]
