# Generated by Django 6.1.1 on 2026-09-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, help_text='Contoh: EURUSD', max_length=10)),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day'), ('W1', '1 Week')], default='H1', max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ForexData',
        ),
        migrations.AddIndex(
            model_name='forexcandle',
            index=models.Index(fields=['pair', 'timeframe', 'timestamp'], name='forex_forex_pair_8751c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forexcandle',
            unique_together={('pair', 'timeframe', 'timestamp')},
        ),
    ]
