# Generated by Django 6.1.1 on 2026-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energystock',
            name='ticker',
            field=models.CharField(help_text='Kode emiten, misal: ADRO', max_length=10),
        ),
    ]
