# Generated by Django 6.1.1 on 2026-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Kode emiten, misal: BIRD, GIAA, TMAS, ASSA', max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
